/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) UAV_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {7, 1, 1};
static const casadi_int casadi_s3[3] = {17, 1, 1};

/* UAV_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[7])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a01=2.;
  a02=arg[2]? arg[2][0] : 0;
  a03=arg[1]? arg[1][7] : 0;
  a04=arg[3]? arg[3][0] : 0;
  a03=(a03/a04);
  a05=(a02*a03);
  a05=(a01*a05);
  a06=(a00*a05);
  a07=arg[0]? arg[0][3] : 0;
  a08=(a07+a07);
  a09=arg[1]? arg[1][9] : 0;
  a09=(a09/a04);
  a10=(a02*a09);
  a10=(a01*a10);
  a11=(a08*a10);
  a12=arg[0]? arg[0][6] : 0;
  a13=arg[1]? arg[1][8] : 0;
  a13=(a13/a04);
  a02=(a02*a13);
  a02=(a01*a02);
  a04=(a12*a02);
  a11=(a11+a04);
  a06=(a06-a11);
  a11=arg[0]? arg[0][10] : 0;
  a04=5.0000000000000000e-01;
  a14=arg[1]? arg[1][6] : 0;
  a15=(a04*a14);
  a16=(a11*a15);
  a06=(a06-a16);
  a16=arg[0]? arg[0][11] : 0;
  a17=arg[1]? arg[1][5] : 0;
  a18=(a04*a17);
  a19=(a16*a18);
  a06=(a06+a19);
  a19=arg[0]? arg[0][12] : 0;
  a20=arg[1]? arg[1][4] : 0;
  a21=(a04*a20);
  a22=(a19*a21);
  a06=(a06-a22);
  a22=25.;
  a23=(a22*a12);
  a23=(a23*a14);
  a24=(a22*a00);
  a24=(a24*a17);
  a23=(a23+a24);
  a24=arg[0]? arg[0][4] : 0;
  a25=(a22*a24);
  a25=(a25*a20);
  a23=(a23+a25);
  a25=(a22*a07);
  a26=arg[1]? arg[1][3] : 0;
  a25=(a25*a26);
  a23=(a23+a25);
  a08=(a08*a23);
  a06=(a06-a08);
  a08=1.;
  a25=casadi_sq(a07);
  a27=casadi_sq(a24);
  a25=(a25+a27);
  a27=casadi_sq(a00);
  a27=(a25+a27);
  a28=casadi_sq(a12);
  a27=(a27+a28);
  a27=(a08-a27);
  a28=(a27*a26);
  a28=(a22*a28);
  a06=(a06+a28);
  if (res[0]!=0) res[0][3]=a06;
  a06=(a00*a02);
  a28=(a24+a24);
  a10=(a28*a10);
  a06=(a06-a10);
  a10=(a12*a05);
  a06=(a06+a10);
  a10=(a16*a15);
  a06=(a06-a10);
  a10=(a11*a18);
  a06=(a06-a10);
  a20=(a27*a20);
  a20=(a22*a20);
  a06=(a06+a20);
  a28=(a28*a23);
  a06=(a06-a28);
  a04=(a04*a26);
  a26=(a19*a04);
  a06=(a06+a26);
  if (res[0]!=0) res[0][4]=a06;
  a06=(a24*a02);
  a26=(a07*a05);
  a06=(a06+a26);
  a26=(a19*a15);
  a06=(a06-a26);
  a17=(a27*a17);
  a17=(a22*a17);
  a06=(a06+a17);
  a17=(a11*a21);
  a06=(a06+a17);
  a17=(a00+a00);
  a17=(a17*a23);
  a06=(a06-a17);
  a17=(a16*a04);
  a06=(a06-a17);
  if (res[0]!=0) res[0][5]=a06;
  a05=(a24*a05);
  a02=(a07*a02);
  a05=(a05-a02);
  a27=(a27*a14);
  a22=(a22*a27);
  a05=(a05+a22);
  a22=(a19*a18);
  a05=(a05+a22);
  a22=(a16*a21);
  a05=(a05+a22);
  a22=(a12+a12);
  a22=(a22*a23);
  a05=(a05-a22);
  a22=(a11*a04);
  a05=(a05+a22);
  if (res[0]!=0) res[0][6]=a05;
  a05=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][7]=a05;
  a05=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][8]=a05;
  a05=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][9]=a05;
  a05=arg[3]? arg[3][5] : 0;
  a22=(a05*a11);
  a23=arg[3]? arg[3][6] : 0;
  a27=(a23*a16);
  a22=(a22+a27);
  a27=arg[3]? arg[3][3] : 0;
  a14=(a27*a19);
  a22=(a22+a14);
  a14=arg[3]? arg[3][1] : 0;
  a02=(a14*a27);
  a06=casadi_sq(a05);
  a02=(a02-a06);
  a06=arg[3]? arg[3][2] : 0;
  a17=(a06*a27);
  a26=casadi_sq(a23);
  a17=(a17-a26);
  a26=(a14*a17);
  a28=arg[3]? arg[3][4] : 0;
  a20=(a28*a27);
  a10=(a23*a05);
  a10=(a20-a10);
  a29=(a28*a10);
  a26=(a26-a29);
  a29=(a28*a23);
  a30=(a06*a05);
  a30=(a29-a30);
  a31=(a05*a30);
  a26=(a26+a31);
  a02=(a02/a26);
  a31=arg[1]? arg[1][11] : 0;
  a02=(a02*a31);
  a32=(a14*a23);
  a33=(a28*a05);
  a33=(a32-a33);
  a33=(a33/a26);
  a34=arg[1]? arg[1][12] : 0;
  a33=(a33*a34);
  a02=(a02-a33);
  a33=(a05*a23);
  a20=(a20-a33);
  a20=(a20/a26);
  a33=arg[1]? arg[1][10] : 0;
  a20=(a20*a33);
  a02=(a02-a20);
  a20=(a22*a02);
  a35=(a28*a11);
  a36=(a06*a16);
  a35=(a35+a36);
  a36=(a23*a19);
  a35=(a35+a36);
  a36=(a14*a06);
  a37=casadi_sq(a28);
  a36=(a36-a37);
  a36=(a36/a26);
  a36=(a36*a34);
  a37=(a05*a28);
  a32=(a32-a37);
  a32=(a32/a26);
  a32=(a32*a31);
  a36=(a36-a32);
  a32=(a05*a06);
  a29=(a29-a32);
  a29=(a29/a26);
  a29=(a29*a33);
  a36=(a36+a29);
  a29=(a35*a36);
  a20=(a20-a29);
  a29=(a16*a36);
  a32=(a19*a02);
  a29=(a29-a32);
  a32=(a14*a29);
  a20=(a20+a32);
  a30=(a30/a26);
  a30=(a30*a34);
  a10=(a10/a26);
  a10=(a10*a31);
  a30=(a30-a10);
  a17=(a17/a26);
  a17=(a17*a33);
  a30=(a30+a17);
  a17=(a19*a30);
  a33=(a11*a36);
  a17=(a17-a33);
  a33=(a28*a17);
  a20=(a20+a33);
  a33=(a11*a02);
  a26=(a16*a30);
  a33=(a33-a26);
  a26=(a05*a33);
  a20=(a20+a26);
  a26=(a07*a15);
  a20=(a20-a26);
  a26=(a24*a18);
  a20=(a20-a26);
  a26=(a00*a21);
  a20=(a20+a26);
  a26=(a12*a04);
  a20=(a20+a26);
  if (res[0]!=0) res[0][10]=a20;
  a14=(a14*a11);
  a16=(a28*a16);
  a14=(a14+a16);
  a19=(a05*a19);
  a14=(a14+a19);
  a19=(a14*a36);
  a28=(a28*a29);
  a19=(a19+a28);
  a06=(a06*a17);
  a19=(a19+a06);
  a22=(a22*a30);
  a19=(a19-a22);
  a22=(a23*a33);
  a19=(a19+a22);
  a22=(a24*a15);
  a19=(a19-a22);
  a22=(a07*a18);
  a19=(a19+a22);
  a22=(a12*a21);
  a19=(a19+a22);
  a22=(a00*a04);
  a19=(a19-a22);
  if (res[0]!=0) res[0][11]=a19;
  a05=(a05*a29);
  a14=(a14*a02);
  a05=(a05-a14);
  a35=(a35*a30);
  a05=(a05+a35);
  a23=(a23*a17);
  a05=(a05+a23);
  a27=(a27*a33);
  a05=(a05+a27);
  a15=(a00*a15);
  a05=(a05-a15);
  a18=(a12*a18);
  a05=(a05+a18);
  a21=(a07*a21);
  a05=(a05-a21);
  a04=(a24*a04);
  a05=(a05+a04);
  if (res[0]!=0) res[0][12]=a05;
  a25=(a01*a25);
  a08=(a08-a25);
  a08=(a08*a09);
  a09=(a24*a00);
  a25=(a12*a07);
  a09=(a09-a25);
  a09=(a01*a09);
  a09=(a09*a13);
  a08=(a08+a09);
  a07=(a07*a00);
  a12=(a12*a24);
  a07=(a07+a12);
  a01=(a01*a07);
  a01=(a01*a03);
  a08=(a08+a01);
  if (res[0]!=0) res[0][13]=a08;
  if (res[0]!=0) res[0][14]=a30;
  if (res[0]!=0) res[0][15]=a02;
  if (res[0]!=0) res[0][16]=a36;
  return 0;
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UAV_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UAV_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void UAV_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void UAV_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int UAV_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int UAV_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real UAV_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UAV_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UAV_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UAV_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UAV_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
