/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) UAV_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {7, 1, 1};
static const casadi_int casadi_s3[3] = {17, 1, 1};

/* UAV_model_expl_vde_adj:(i0[13],i1[13],i2[4],i3[7])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a01=2.;
  a02=arg[2]? arg[2][0] : 0;
  a03=arg[1]? arg[1][7] : 0;
  a04=arg[3]? arg[3][0] : 0;
  a03=(a03/a04);
  a05=(a02*a03);
  a05=(a01*a05);
  a06=(a00*a05);
  a07=arg[0]? arg[0][3] : 0;
  a08=(a07+a07);
  a09=arg[1]? arg[1][9] : 0;
  a09=(a09/a04);
  a10=(a02*a09);
  a10=(a01*a10);
  a08=(a08*a10);
  a11=arg[0]? arg[0][6] : 0;
  a12=arg[1]? arg[1][8] : 0;
  a12=(a12/a04);
  a02=(a02*a12);
  a02=(a01*a02);
  a04=(a11*a02);
  a08=(a08+a04);
  a06=(a06-a08);
  a08=arg[0]? arg[0][10] : 0;
  a04=5.0000000000000000e-01;
  a13=arg[1]? arg[1][6] : 0;
  a13=(a04*a13);
  a14=(a08*a13);
  a06=(a06-a14);
  a14=arg[0]? arg[0][11] : 0;
  a15=arg[1]? arg[1][5] : 0;
  a15=(a04*a15);
  a16=(a14*a15);
  a06=(a06+a16);
  a16=arg[0]? arg[0][12] : 0;
  a17=arg[1]? arg[1][4] : 0;
  a17=(a04*a17);
  a18=(a16*a17);
  a06=(a06-a18);
  if (res[0]!=0) res[0][3]=a06;
  a06=(a00*a02);
  a18=arg[0]? arg[0][4] : 0;
  a19=(a18+a18);
  a19=(a19*a10);
  a06=(a06-a19);
  a19=(a11*a05);
  a06=(a06+a19);
  a19=(a14*a13);
  a06=(a06-a19);
  a19=(a08*a15);
  a06=(a06-a19);
  a19=arg[1]? arg[1][3] : 0;
  a04=(a04*a19);
  a19=(a16*a04);
  a06=(a06+a19);
  if (res[0]!=0) res[0][4]=a06;
  a06=(a18*a02);
  a19=(a07*a05);
  a06=(a06+a19);
  a19=(a16*a13);
  a06=(a06-a19);
  a19=(a08*a17);
  a06=(a06+a19);
  a19=(a14*a04);
  a06=(a06-a19);
  if (res[0]!=0) res[0][5]=a06;
  a05=(a18*a05);
  a02=(a07*a02);
  a05=(a05-a02);
  a02=(a16*a15);
  a05=(a05+a02);
  a02=(a14*a17);
  a05=(a05+a02);
  a02=(a08*a04);
  a05=(a05+a02);
  if (res[0]!=0) res[0][6]=a05;
  a05=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][7]=a05;
  a05=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][8]=a05;
  a05=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][9]=a05;
  a05=arg[3]? arg[3][5] : 0;
  a02=(a05*a08);
  a06=arg[3]? arg[3][6] : 0;
  a19=(a06*a14);
  a02=(a02+a19);
  a19=arg[3]? arg[3][3] : 0;
  a10=(a19*a16);
  a02=(a02+a10);
  a10=arg[3]? arg[3][1] : 0;
  a20=(a10*a19);
  a21=casadi_sq(a05);
  a20=(a20-a21);
  a21=arg[3]? arg[3][2] : 0;
  a22=(a21*a19);
  a23=casadi_sq(a06);
  a22=(a22-a23);
  a23=(a10*a22);
  a24=arg[3]? arg[3][4] : 0;
  a25=(a24*a19);
  a26=(a06*a05);
  a26=(a25-a26);
  a27=(a24*a26);
  a23=(a23-a27);
  a27=(a24*a06);
  a28=(a21*a05);
  a28=(a27-a28);
  a29=(a05*a28);
  a23=(a23+a29);
  a20=(a20/a23);
  a29=arg[1]? arg[1][11] : 0;
  a20=(a20*a29);
  a30=(a10*a06);
  a31=(a24*a05);
  a31=(a30-a31);
  a31=(a31/a23);
  a32=arg[1]? arg[1][12] : 0;
  a31=(a31*a32);
  a20=(a20-a31);
  a31=(a05*a06);
  a25=(a25-a31);
  a25=(a25/a23);
  a31=arg[1]? arg[1][10] : 0;
  a25=(a25*a31);
  a20=(a20-a25);
  a25=(a02*a20);
  a33=(a24*a08);
  a34=(a21*a14);
  a33=(a33+a34);
  a34=(a06*a16);
  a33=(a33+a34);
  a34=(a10*a21);
  a35=casadi_sq(a24);
  a34=(a34-a35);
  a34=(a34/a23);
  a34=(a34*a32);
  a35=(a05*a24);
  a30=(a30-a35);
  a30=(a30/a23);
  a30=(a30*a29);
  a34=(a34-a30);
  a30=(a05*a21);
  a27=(a27-a30);
  a27=(a27/a23);
  a27=(a27*a31);
  a34=(a34+a27);
  a27=(a33*a34);
  a25=(a25-a27);
  a27=(a14*a34);
  a30=(a16*a20);
  a27=(a27-a30);
  a30=(a10*a27);
  a25=(a25+a30);
  a28=(a28/a23);
  a28=(a28*a32);
  a26=(a26/a23);
  a26=(a26*a29);
  a28=(a28-a26);
  a22=(a22/a23);
  a22=(a22*a31);
  a28=(a28+a22);
  a22=(a16*a28);
  a31=(a08*a34);
  a22=(a22-a31);
  a31=(a24*a22);
  a25=(a25+a31);
  a31=(a08*a20);
  a23=(a14*a28);
  a31=(a31-a23);
  a23=(a05*a31);
  a25=(a25+a23);
  a23=(a07*a13);
  a25=(a25-a23);
  a23=(a18*a15);
  a25=(a25-a23);
  a23=(a00*a17);
  a25=(a25+a23);
  a23=(a11*a04);
  a25=(a25+a23);
  if (res[0]!=0) res[0][10]=a25;
  a10=(a10*a08);
  a14=(a24*a14);
  a10=(a10+a14);
  a16=(a05*a16);
  a10=(a10+a16);
  a16=(a10*a34);
  a24=(a24*a27);
  a16=(a16+a24);
  a21=(a21*a22);
  a16=(a16+a21);
  a02=(a02*a28);
  a16=(a16-a02);
  a02=(a06*a31);
  a16=(a16+a02);
  a02=(a18*a13);
  a16=(a16-a02);
  a02=(a07*a15);
  a16=(a16+a02);
  a02=(a11*a17);
  a16=(a16+a02);
  a02=(a00*a04);
  a16=(a16-a02);
  if (res[0]!=0) res[0][11]=a16;
  a05=(a05*a27);
  a10=(a10*a20);
  a05=(a05-a10);
  a33=(a33*a28);
  a05=(a05+a33);
  a06=(a06*a22);
  a05=(a05+a06);
  a19=(a19*a31);
  a05=(a05+a19);
  a13=(a00*a13);
  a05=(a05-a13);
  a15=(a11*a15);
  a05=(a05+a15);
  a17=(a07*a17);
  a05=(a05-a17);
  a04=(a18*a04);
  a05=(a05+a04);
  if (res[0]!=0) res[0][12]=a05;
  a05=1.;
  a04=casadi_sq(a07);
  a17=casadi_sq(a18);
  a04=(a04+a17);
  a04=(a01*a04);
  a05=(a05-a04);
  a05=(a05*a09);
  a09=(a18*a00);
  a04=(a11*a07);
  a09=(a09-a04);
  a09=(a01*a09);
  a09=(a09*a12);
  a05=(a05+a09);
  a07=(a07*a00);
  a11=(a11*a18);
  a07=(a07+a11);
  a01=(a01*a07);
  a01=(a01*a03);
  a05=(a05+a01);
  if (res[0]!=0) res[0][13]=a05;
  if (res[0]!=0) res[0][14]=a28;
  if (res[0]!=0) res[0][15]=a20;
  if (res[0]!=0) res[0][16]=a34;
  return 0;
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UAV_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UAV_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void UAV_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void UAV_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int UAV_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int UAV_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real UAV_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UAV_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UAV_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UAV_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UAV_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int UAV_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
